### PR TITLE
(BROKEN) Added a SWIFT Sample - RBQFetchedResultsControllerSwiftExample

### PR DESCRIPTION
**Pull request by mgleason**
Hi Adam,

Sorry i mis-read your post today.   This pull request adds a 2nd example, which might serve 2 purposes:

1) Eventually act as a example of how to use RBQFetchedResultsController with Swift (though not yet because it doesn't work :)
2) As I mentioned, it appears that RBQFetchedResultsController isn't returning any records.  If you have any interest/time in debugging, this might act as a starting point.  

If you'd prefer to that I debug, that's fine as well - any suggestions on where to look/get started would be appreciated.

Note that, In addition, I needed to make the following modifications to the #imports
in the following files in the RBQFetchedResultsControllerSwiftExample
pod:

FILE                                 OLD Value
NEW value
RBQSafeRealmObject.h  #import "RLMProperty.h"   #import
<Realm/RLMProperty.h>
RLMObject+Notifications.h #import "RLMObject.h"  #import
<Realm/RLMObject.h>
RLMRealm+Notifications.h  #import "RLMRealm.h"  #import
<Realm/RLMRealm.h>
RLMObject+SafeObject.h  #import "RLMObject.h"   #import
<Realm/RLMObject.h>
RLMObject+Utilities.h        #import "RLMObject.h"   #import
<Realm/RLMObject.h>

### CODE REVIEW

**Comment by bigfish24** [comment]
Ok well the issue is that Swift Classes are identified with a different string than Obj-C classes. So the logic is broken because the FRC represents the original RLMObject in its cache by storing the NSString of the Class name. It then reproduces the object by calling the function NSClassFromString() to get the Class to call the RLMObject class method to retrieve the object by primary key.

So the problem is that the class name it is storing is "TestObject" versus "RBQFetchedResultsControllerSwiftExample.TestObject"

I recalled noticing this when reviewing Realm's code because they have two methods to identify and clean up Swift classes in RLMSwiftSupport

So I will need to rework the logic to handle this issue since it touches the RBQFetchRequest and RBQFRC.

**Comment by Brisdo** [comment]
Thanks Adam!

**Comment by bigfish24** [comment]
One thing I noticed is line 87 in ExampleTableViewController.swift should not have "let" but rather just be:
```
fetchedResultsController = RBQFetchedResultsController(fetchRequest: fetchRequest, sectionNameKeyPath: "sectionName", cacheName: "testCache")
```

I added a class method in RBQFetchRequest to pass in the Class and derive the entity name from that, and also adjusted the FRC to use the entity name from it's fetch request, and now the tableview shows all the rows. However, not sure if I like this approach. Wondering if there is a cleaner way. Will continue to play with it...

**Comment by mgleason** [comment]
>> Line 87
Good catch.

>> I added a class method...
Awesome!  Could you post what you added?

**Comment by bigfish24** [comment]
Ok, have a better way to fix this so that it hides the complexity from the developer.

in RBQFetchRequest you can add the follow class method:

```
+ (NSString *)verifyEntityName:(NSString *)entityName
{
    Class objcClass = NSClassFromString(entityName);
    
    if (objcClass) {
        return entityName;
    }
    
    NSString *appName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"];

    NSString *swiftClassName = [NSString stringWithFormat:@"%@.%@",appName,entityName];
    
    return swiftClassName;
}
```

then in the two other constructor class methods, just add the call:

```
entityName = [RBQFetchRequest verifyEntityName:entityName];
    
RBQFetchRequest *fetchRequest = [[RBQFetchRequest alloc] initWithEntityName:entityName
                                                                        inRealm:realm];
```

Finally, replace the class method classNameForObject: in RLMObject+Utilities category with this:

```
+ (NSString *)classNameForObject:(RLMObject *)object
{
    // Returns the class name in code (i.e. "TestObject" not "RLMAccessor_V0_TestObject")
    NSString *className = [[object class] className];
    
    Class objectClass = NSClassFromString(className);
    
    // If we have Obj-C class return the name
    if (objectClass) {
        return className;
    }
    
    NSString *appName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"];
    
    NSString *swiftClassName = [NSString stringWithFormat:@"%@.%@",appName,className];
    
    return swiftClassName;
}
```

**Comment by bigfish24** [comment]
Ok this issue should be fixed in v1.7.4: https://github.com/Roobiq/RBQFetchedResultsController/releases

**Comment by mgleason** [comment]
Awesome thanks!

Unfortunately, I can't quite get it to work.  2 things:

1)  Had to re-do the #imports to get it to compile (using Cocoapods):

FILE                                       OLD Value                            NEW value
RBQSafeRealmObject.h    #import "RLMProperty.h"  --> #import <Realm/RLMProperty.h>
RLMObject+Notifications.h #import "RLMObject.h"    --> #import <Realm/RLMObject.h>
RLMRealm+Notifications.h #import "RLMRealm.h"    --> #import <Realm/RLMRealm.h>
RLMObject+SafeObject.h   #import "RLMObject.h"    --> #import <Realm/RLMObject.h>
RLMObject+Utilities.h          #import "RLMObject.h"   --> #import <Realm/RLMObject.h>

 2) Although the section names now have data in the tableview headers, the cells are still blank.  In RBQObjectCacheObject.m in [RBQObjectCacheObject objectInRealm:realm forCacheObject:cacheObject], for some reason, it looks as though realClass ends up nil when running the Swift version, but the Objective-C version gets "(Class) TestObject"

**Comment by bigfish24** [comment]
I don't understand the import changes you mentioned?

**Comment by mgleason** [comment]
Sorry, it seems to be cutting off 1/3 of the lines

FILE                                       OLD Value                     
       NEW value
```
RBQSafeRealmObject.h    #import "RLMProperty.h"   --> #import <Realm/RLMProperty.h>
RLMObject+Notifications.h #import "RLMObject.h"     --> #import <Realm/RLMObject.h>
RLMRealm+Notifications.h #import "RLMRealm.h"     --> #import <Realm/RLMRealm.h>
RLMObject+SafeObject.h   #import "RLMObject.h"     --> #import <Realm/RLMObject.h>
RLMObject+Utilities.h         #import "RLMObject.h"     --> #import <Realm/RLMObject.h>
```

**Comment by bigfish24** [comment]
Hmm all of that has been fixed. I think there is an issue with Cocoapods and submodules. The changes are not being reflected when installed through that. All of this was fixed.

**Comment by bigfish24** [comment]
Ok just updated the podspec to v1.7.5 and tried the install. It now is installing the proper submodule commits.... so give it a try.

**Comment by mgleason** [comment]
Terrific - that did it!

**Comment by bigfish24** [comment]
Excellent, not sure why the submidules were off. Let me know if you run into any other issues.

**Pull request closed without merging**
