### PR TITLE
Version 3.0 --> Carthage support!

### PR DESCRIPTION
**Pull request by bigfish24**
This PR is based primarily off of: https://github.com/Roobiq/RBQFetchedResultsController/pull/57 by @ataibarkai. I needed to continue his awesome work to make sure Cocoapods still worked and then did a general file/folder clean up.

### CODE REVIEW

**Comment by bigfish24** [comment]
@ataibarkai I couldn't push to your fork, so I created this branch that includes all of your changes and then I added further work to clean up everything and ensure Cocoapods still works. Please review... and because the bulk of the work is yours, feel free to create a new branch off of this and a new PR. Would rather the PR be based on your request to merge.

**Comment by bigfish24** [comment]
@ataibarkai I would suggest that you create a new branch off of this and then rebase your commits so that you can squash the history a bit. A lot of those commits are directory changes that I then had to adjust a bit, so might as well squash them down so the history is cleaner. I can then merge a PR off of that.

**Comment by courtneybowdon** [comment]
Can you please change it back that was not me but an evil gf

**Comment by courtneybowdon** [comment]
How can I regain the ability to install with pics again

**Comment by ataibarkai** [comment]
@bigfish24 ok looks great.
I'll try to get to it in the next 1-2 days.

**Comment by bigfish24** [comment]
This PR supersedes this one: https://github.com/Roobiq/RBQFetchedResultsController/pull/61

**Comment by ataibarkai** [comment]
@bigfish24 just submitted the (hopefully final!) pull request.

I'm sorry it took me a little while, I was a bit busy over the last few days. 
Thanks for your help + extra tidy-ups.

I'll see what extra changes you've made and try to replicated them on the RealmMapView project, hopefully we can put that one behind us too pretty soon.

Might take me a little while though, I'm going to be fairly busy over the next 2 weeks or so.

**Comment by bigfish24** [comment]
@ataibarkai awesome thanks for the help with this. I was going to check out what needs to be done with the map view too. I am out of town this weekend, so won't be till next week though. Will merge your PR this afternoon.

**Comment by ataibarkai** [comment]
@bigfish24 👍👍👍

**Pull request closed without merging**
